sudo: false
language: python
dist: trusty

matrix:
  include:
    # Default Python
    - env:
      - TOXENV=flake8
      - TOXENV=markdown-lint
      - TOXENV=linkchecker
      - TOXENV=jshint
      - TOXENV=csslint
    # Python version specific
    - python: '2.6'
      env: TOXENV=py26-integration, py26-min-req, py26-unittests
    - python: '2.7'
      env: TOXENV=py27-integration, py27-min-req, py27-unittests
    - python: '3.3'
      env: TOXENV=py33-integration, py33-min-req, py33-unittests
    - python: '3.4'
      env: TOXENV=py34-integration, py34-min-req, py34-unittests
    - python: '3.5'
      env: TOXENV=py35-integration, py35-min-req, py35-unittests
    - python: 'pypy'
      env: TOXENV=pypy-integration, pypy-min-req, pypy-unittests
    - python: 'pypy3'
      env: TOXENV=pypy3-integration, pypy3-min-req, pypy3-unittests
  allow_failures:
    - env: TOXENV=pypy3-integration
    - env: TOXENV=pypy3-min-req
    - env: TOXENV=pypy3-unittests

before_install: pip install codecov
install:
  - pip install tox
  - gem install mdl
  - npm install -g jshint
  - npm install -g csslint
script:
  - git clean -f -d -x
  - tox

after_success: codecov

deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: "sdist bdist_wheel"
  password:
    secure: b4f6y1xw5B/RXXnOu6JIaNcgOBZ0/CkNaMeEXsoQSewYZNwobLPYALY9WaaOblarwrVa5NRD3e4x6SoL1/1NzQxfhCNMn7L82sssmtevnK+mSuUp4IZQa8WKyz+xLfnk28TlHgQbctAU9NaeQ6GuEflTRD7Bp8+xJ1C7h+yBUnw=
  on:
    tags: true
    repo: mkdocs/mkdocs
    condition: "$TOXENV = py27-integration"
