sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - travis_retry pip install codecov tox-travis
  - travis_retry gem install mdl
  - travis_retry npm install -g csslint jshint

script:
  - git clean -f -d -x
  - tox

after_success: codecov

deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: "sdist bdist_wheel"
  password:
    secure: b4f6y1xw5B/RXXnOu6JIaNcgOBZ0/CkNaMeEXsoQSewYZNwobLPYALY9WaaOblarwrVa5NRD3e4x6SoL1/1NzQxfhCNMn7L82sssmtevnK+mSuUp4IZQa8WKyz+xLfnk28TlHgQbctAU9NaeQ6GuEflTRD7Bp8+xJ1C7h+yBUnw=
  on:
    tags: true
    repo: mkdocs/mkdocs
    condition: "$TOXENV = py27-integration"
