site_name: NSI-Aventure
site_url: https://nsi-mayotte.github.io/nsi-aventure-docs/
site_description: Documentation en Markdown pour NSI-Aventure.
site_author: NSI-Aventure Team

repo_url: https://github.com/nsi-mayotte/nsi-aventure-docs/
#edit_uri: blob/master/docs/

theme:
  name: readthedocs
  locale: fr
  #analytics: {gtag: 'G-274394082'}
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Guide Orga: guide-orga/
  - Guide Dev: guide-dev/

home: guide-orga/content.md

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click

copyright: Copyright &copy; 2014 <a href="https://twitter.com/starletdreaming">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

hooks:
  - docs/hooks.py

plugins:
  - search
  #- redirects:
      #redirect_maps:
        #user-guide/plugins.md: dev-guide/plugins.md
        #user-guide/custom-themes.md: dev-guide/themes.md
        #user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
  - autorefs
  - literate-nav:
      nav_file: content.md
      implicit_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true

watch:
  - mkdocs
