name: deploy-release

on:
  push:
    tags:
    - '*'

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Check if Portable Object translation files updates are missing
        run: |
          for locale in $(ls mkdocs/themes/mkdocs/locales/); do python setup.py update_catalog -t mkdocs -l ${locale}; done
          for locale in $(ls mkdocs/themes/readthedocs/locales/); do python setup.py update_catalog -t readthedocs -l ${locale}; done
          git diff --ignore-matching-lines 'POT-Creation-Date' --exit-code
        shell: bash
      - name: Compile localization message files
        run: |
          pybabel compile -d mkdocs/themes/mkdocs/locales
          pybabel compile -d mkdocs/themes/readthedocs/locales
      - name: Build
        run: |
          python setup.py bdist_wheel sdist --formats gztar
      - name: Publish
        if: success()
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
