name: deploy-release

on:
  push:
    tags:
    - '*'

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U hatch babel
      - name: Compile localization message files
        run: |
          pybabel compile --statistics --directory mkdocs/themes/mkdocs/locales
          pybabel compile --statistics --directory mkdocs/themes/readthedocs/locales
      - name: Build
        run: |
          hatch build
      - name: Publish
        run: |
          hatch publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
